version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    links:
      - webapi1

  webapi1:
    image: ${DOCKER_REGISTRY-}webapi1
    build:
      context: .
      dockerfile: WebAPI1/Dockerfile

