version: '3.4'

services:
  webapplication1:
    links:
      - webapi1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapi1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

